### ISSUE TITLE
VLC keeps opened after pyRadio closed

### ISSUE THREAD

**Issue by baruchiro** [coderholic/pyradio#117]
Hi, I'm using `pyradio` on Windows with the VLC media player.

If I clicking on `Esc` when `pyradio` is on, sometimes it closed well, but sometimes it gets stuck with `Thank you for using PyRadio`, the `VLC` process still up and I still heard the radio, and `pyradio` holding the terminal.

In any way, if I'm closing the terminal running `pyradio` without closing `pyradio` manually, the terminal closed but the VLC process still up and running.

**Comment by s-n-g** [comment]
Hi @baruchiro 

Which version of windows are you on?

**Comment by baruchiro** [comment]
```cmd
> ver

Microsoft Windows [Version 10.0.20270.1]
```

**Comment by s-n-g** [comment]
ok, I haven't managed to reproduce it on my Windows 10, but it was there on Windows 7 (plus some other issues as well).

Anyways, please do test the latest release, and if you still got a proble, please

1. execute

```pyradio -d```

and post the file called **pyradio.log** found in your home folder.

2. post any messages you may have on windows console

I hope I got it right...

**Comment by baruchiro** [comment]
[pyradio.log](https://github.com/coderholic/pyradio/files/5690526/pyradio.log)

The problem still exists, log attached, no output in the console.

**Comment by s-n-g** [comment]
How do you exit **PyRadio**?
Do you press "q" or "ESC" in its window or do just close the window from the taskbar?

**Comment by baruchiro** [comment]
I'm just closing the window from the X button:
![image](https://user-images.githubusercontent.com/17686879/102199699-95a80880-3ecc-11eb-8c6a-cc68a2adac97.png)

And this is the easiest way to reproduce, I still don't know how to reproduce the problem when I'm getting two VLC processes running when the pyradio is open.

**Comment by s-n-g** [comment]
Ok, I imagined that would be the case, just making sure.
I think I got it now

Having two VLC processes should not be happening any more; that's what I fixed in 0.8.8.1
But, hey, we can keep testing it

**Comment by baruchiro** [comment]
So do you want me to pull the latest changes to check if it solved?

Or you think the problem is still there?

I didn't understand, sorry

**Comment by s-n-g** [comment]
No, no, not yet... Sorry I wasn't clear before...

I am working on making it detect that the console is closed and stop the player, save the playlist (if modified), etc.
I will notify you when it's done...

BTW, do you use ```git```?
Can I push it to a branch and have you download it from there, or would you rather have a zip file?
I would like to avoid making a new release until it's ok

**Comment by baruchiro** [comment]
Sure Sure I'm using `git`, currently on `master`.

**Comment by s-n-g** [comment]
ok, ready for a test..

Just execute this one to get the new branch

```git checkout --track origin/baruchiro```

**Comment by baruchiro** [comment]
OK, closing the terminal also closing the VLC process. Thanks!

About the other side of the problem, multiple VLC processes when moving between stations, I don't know how to reproduce, and my suggestion is to close this issue until it will reproduce (if any)...

Thanks!!!

**Comment by s-n-g** [comment]
Ok, closing...
Thank you for reporting this one, it really made a difference!
